1.4 Exercice avec solution


Créer une fonction initialisation permettant de retourner M une matrice aléatoire de dimension
(m,n+1) avec une colonne biais remplie de 1 tout à droite


In [7]:
import numpy as np

def mat(m,n):
    m=int(input('nbre de ligne'))
    n=int(input('nbre de colonne'))
    return  np.random.randn(m,n+1)

mat(3,2)

nbre de ligne2
nbre de colonne3


array([[ 1.84556463,  0.80362933,  0.80414204, -0.92536389],
       [ 0.12692906,  1.65587926,  2.36604976,  1.78996321]])

2.4 Exercice et Solution


Standardisez la matrice suivante, c’est a dire effectuez le calcul suivant : A =
A−mean(Acolonne)
std(Acolonne)


In [8]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [9]:
S = A-np.mean(A,axis=0)//np.std(A,axis=0)
S

array([[43., 45., 62., 66., 65.],
       [ 8., 81., 19., 35., 85.],
       [69., 86., 86., 11., 56.],
       [64., 37., 85., 45., 86.],
       [80., 35., 23., 76., 70.],
       [ 8., 18., 78., 68., 77.],
       [46., 62., 80., 98., 86.],
       [48., 27., 17., 18., 12.],
       [38., 30., 63.,  8., 55.],
       [31., 29., 72., 22., 33.]])

In [10]:
print(np.mean(S,axis=0))

[43.5 45.  58.5 44.7 62.5]


In [11]:
print(np.mean(S,axis=1))

[56.2 45.6 61.6 63.4 56.8 49.8 74.4 24.4 38.8 37.4]


In [12]:
print(np.std(S,axis=0))

[22.66384786 22.28003591 26.5678377  29.36341261 23.2432786 ]


In [13]:
print(np.std(S,axis=1))

[10.06777036 31.74649587 27.70270745 20.06589146 23.23273553 30.41315505
 18.34775191 12.75303885 19.36388391 17.69293644]


3.1 Exercice


Est ce qu’on peut faire la somme de A(4,1) + B(1,3). Initialiser la matrice A avec des nombres
aléatores et B avec des 1, faite la somme des deux matrices. Interpréter le résultat.

In [5]:
A = np.random.randn(4,1)
A

array([[-1.51230575],
       [ 0.60071763],
       [-0.26055975],
       [-0.57510398]])

In [6]:
B = np.ones((1,3))
B

array([[1., 1., 1.]])

In [16]:
A=np.random.randn(4,1)
A

array([[-0.88180055],
       [-0.44265324],
       [-0.5409163 ],
       [-1.32322737]])

In [18]:
Som=B+A
Som

array([[ 0.11819945,  0.11819945,  0.11819945],
       [ 0.55734676,  0.55734676,  0.55734676],
       [ 0.4590837 ,  0.4590837 ,  0.4590837 ],
       [-0.32322737, -0.32322737, -0.32322737]])